import { useEffect, useState } from 'react';
import api from '../api/axios';
import EventCard from '../components/EventCard';
import StarRating from '../components/StarRating';
import { useAuth } from '../context/AuthContext';
import { useToast } from '../components/Toast';

const CATEGORIES = ['All', 'Technical', 'Cultural', 'Business', 'Gaming', 'Creative'];

function ReviewsModal({ event, onClose }) {
    const { user } = useAuth();
    const { addToast } = useToast();
    const [reviewsData, setReviewsData] = useState({ reviews: [], avgRating: 0, distribution: [0,0,0,0,0] });
    const [loading, setLoading] = useState(true);
    const [myRating, setMyRating] = useState(0);
    const [myReviewText, setMyReviewText] = useState('');
    const [submitting, setSubmitting] = useState(false);
    const [aiSummary, setAiSummary] = useState('');
    const [aiLoading, setAiLoading] = useState(false);

    const fetchReviews = async () => {
        try {
            const res = await api.get(`/events/${event.id}/reviews`);
            setReviewsData(res.data.data);
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        if (event) fetchReviews();
    }, [event]);

    const submitReview = async (e) => {
        e.preventDefault();
        if (!myRating) return addToast('Please select a star rating', 'error');
        setSubmitting(true);
        try {
            await api.post(`/events/${event.id}/reviews`, { rating: myRating, content: myReviewText });
            addToast('Review submitted!', 'success');
            setMyRating(0);
            setMyReviewText('');
            fetchReviews();
        } catch (err) {
            addToast(err.response?.data?.message || 'Failed to submit', 'error');
        } finally {
            setSubmitting(false);
        }
    };

    const generateAISummary = async () => {
        if (reviewsData.reviews.length === 0) return addToast('No reviews to summarize yet!', 'error');
        setAiLoading(true);
        try {
            const texts = reviewsData.reviews.map(r => r.content).filter(Boolean);
            const res = await api.post('/ai/event-summary', { reviews: texts });
            setAiSummary(res.data.data);
            addToast('Summary generated by LinkUp AI', 'success');
        } catch (err) {
            addToast('Failed to generate summary', 'error');
        } finally {
            setAiLoading(false);
        }
    };

    if (!event) return null;

    return (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fade-in" onClick={onClose}>
            <div className="glass-card w-full max-w-2xl max-h-[90vh] flex flex-col overflow-hidden border border-white/10 shadow-2xl animate-slide-up" onClick={e => e.stopPropagation()}>
                {/* Modal Header */}
                <div className="px-6 py-4 border-b border-white/5 flex justify-between items-center bg-white/5">
                    <div className="flex items-center gap-3">
                        <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-cyan-500 to-purple-600 flex items-center justify-center text-white text-lg">🎭</div>
                        <div>
                            <h2 className="text-lg font-black text-white leading-tight">{event.name}</h2>
                            <p className="text-xs text-muted uppercase tracking-wider font-bold">Community Feedback</p>
                        </div>
                    </div>
                    <button onClick={onClose} className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center text-muted hover:bg-red-500/20 hover:text-red-400 transition-all duration-200">
                        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M6 18L18 6M6 6l12 12"/></svg>
                    </button>
                </div>

                <div className="overflow-y-auto flex-1 custom-scrollbar">
                    {/* Stats Section */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6 p-6 border-b border-white/5 bg-white/[0.02]">
                        <div className="flex flex-col items-center justify-center p-6 bg-black/40 rounded-3xl border border-white/10">
                            <h3 className="text-5xl font-black gradient-text mb-2">{reviewsData.avgRating}</h3>
                            <StarRating value={reviewsData.avgRating} max={5} readOnly />
                            <p className="text-xs text-muted mt-3 font-medium uppercase tracking-widest">{reviewsData.reviews.length} total reviews</p>
                        </div>

                        <div className="flex flex-col gap-2 justify-center">
                            {[5, 4, 3, 2, 1].map((star, idx) => {
                                const count = reviewsData.distribution?.[5 - star] || 0;
                                const percentage = reviewsData.reviews.length > 0 ? (count / reviewsData.reviews.length) * 100 : 0;
                                return (
                                    <div key={star} className="flex items-center gap-3">
                                        <span className="text-xs font-bold text-muted w-3">{star}</span>
                                        <div className="flex-1 h-2 bg-white/5 rounded-full overflow-hidden">
                                            <div 
                                                className="h-full bg-gradient-to-r from-cyan-500 to-blue-500 transition-all duration-1000"
                                                style={{ width: `${percentage}%` }}
                                            />
                                        </div>
                                        <span className="text-[10px] font-bold text-muted w-8">{Math.round(percentage)}%</span>
                                    </div>
                                );
                            })}
                        </div>
                    </div>

                    <div className="p-6">
                        {/* AI Summary Section */}
                        <div className="relative overflow-hidden p-6 rounded-3xl mb-8 border border-white/10 group">
                            <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/5 to-purple-500/5 opacity-50" />
                            <div className="relative z-10">
                                <div className="flex items-center justify-between mb-4">
                                    <div className="flex items-center gap-2">
                                        <div className="w-8 h-8 rounded-lg bg-cyan-500/20 text-cyan-400 flex items-center justify-center">✨</div>
                                        <span className="text-sm font-black text-white uppercase tracking-wider">AI Intelligence</span>
                                    </div>
                                    <button 
                                        onClick={generateAISummary}
                                        disabled={aiLoading}
                                        className={`text-xs font-bold px-3 py-1.5 rounded-lg border transition-all ${aiLoading ? 'bg-white/5 text-muted' : 'border-cyan-500/50 text-cyan-400 hover:bg-cyan-500/20'}`}
                                    >
                                        {aiLoading ? 'Analyzing...' : aiSummary ? 'Regenerate' : 'Generate Summary'}
                                    </button>
                                </div>
                                
                                {aiSummary ? (
                                    <p className="text-sm text-slate-300 leading-relaxed italic animate-fade-in">
                                        "{aiSummary}"
                                    </p>
                                ) : (
                                    <p className="text-xs text-muted italic">Click generate to see a summary of what people are saying about this event.</p>
                                )}
                            </div>
                        </div>

                        {/* Leave a Review Section */}
                        <div className="mb-10">
                            <h4 className="text-sm font-black text-white mb-4 flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-purple-500" />
                                SHARE YOUR EXPERIENCE
                            </h4>
                            <form onSubmit={submitReview} className="space-y-4">
                                <div className="flex items-center gap-4 p-4 bg-white/5 rounded-2xl border border-white/10">
                                    <span className="text-xs font-bold text-muted uppercase">Rating:</span>
                                    <StarRating value={myRating} onChange={setMyRating} max={5} />
                                </div>
                                <div className="relative">
                                    <textarea
                                        className="w-full bg-white/5 border border-white/10 rounded-2xl p-4 text-sm text-white placeholder:text-muted focus:outline-none focus:border-cyan-500/50 focus:ring-1 focus:ring-cyan-500/50 transition-all duration-300 min-h-[100px] resize-none"
                                        placeholder="What did you love (or not) about this event?"
                                        value={myReviewText}
                                        onChange={(e) => setMyReviewText(e.target.value)}
                                    />
                                </div>
                                <button 
                                    type="submit" 
                                    disabled={submitting || !myRating} 
                                    className={`btn-primary w-full py-4 text-sm font-black tracking-widest uppercase transition-all duration-300 ${submitting ? 'opacity-50' : 'hover:scale-[1.01] hover:shadow-xl hover:shadow-cyan-500/20'}`}
                                >
                                    {submitting ? 'Transmitting...' : 'Post Review'}
                                </button>
                            </form>
                        </div>

                        {/* Reviews List */}
                        <div className="space-y-6">
                            <h4 className="text-sm font-black text-white mb-4 flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-cyan-500" />
                                ALL REVIEWS
                            </h4>
                            {loading ? (
                                <div className="flex flex-col items-center py-12 gap-4">
                                    <div className="w-8 h-8 border-2 border-cyan-500/30 border-t-cyan-500 rounded-full animate-spin" />
                                    <p className="text-xs text-muted font-bold uppercase tracking-wider">Loading stories...</p>
                                </div>
                            ) : reviewsData.reviews.length === 0 ? (
                                <div className="text-center py-12 px-6 border border-dashed border-white/10 rounded-3xl">
                                    <p className="text-3xl mb-3">😶</p>
                                    <p className="text-sm font-bold text-muted uppercase tracking-widest">No reviews yet</p>
                                    <p className="text-xs text-muted/60 mt-1">Be the legend who leaves the first impression!</p>
                                </div>
                            ) : (
                                reviewsData.reviews.map((r, i) => (
                                    <div key={r.id} className="group p-5 rounded-3xl bg-white/[0.03] border border-white/5 hover:border-white/15 transition-all duration-300 animate-slide-up" style={{ animationDelay: `${i * 50}ms` }}>
                                        <div className="flex items-start justify-between mb-4">
                                            <div className="flex items-center gap-3">
                                                <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-500 to-pink-500 flex items-center justify-center text-white font-black text-sm shadow-lg shadow-purple-500/20">
                                                    {r.user.name[0]}
                                                </div>
                                                <div>
                                                    <p className="text-sm font-bold text-white leading-none mb-1">{r.user.name}</p>
                                                    <StarRating value={r.rating} max={5} readOnly size="xs" />
                                                </div>
                                            </div>
                                            <span className="text-[10px] font-black text-muted uppercase tracking-tighter opacity-50">
                                                {new Date(r.createdAt).toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' })}
                                            </span>
                                        </div>
                                        <p className="text-sm text-slate-400 leading-relaxed font-medium">
                                            {r.content}
                                        </p>
                                    </div>
                                ))
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default function Events() {
    const { user } = useAuth();
    const [events, setEvents] = useState([]);
    const [loading, setLoading] = useState(true);
    const [category, setCategory] = useState('All');
    const [joinedIds, setJoinedIds] = useState(new Set());
    const [reviewModalEvent, setReviewModalEvent] = useState(null);

    const fetchEvents = async () => {
        const res = await api.get('/events', { params: category !== 'All' ? { category } : {} });
        const data = res.data.data;
        setEvents(data);
        setJoinedIds(new Set(
            data.filter(e => e.joins?.some(j => j.userId === user.id)).map(e => e.id)
        ));
        setLoading(false);
    };

    useEffect(() => { fetchEvents(); }, [category]);

    return (
        <div className="max-w-6xl mx-auto px-4 py-8 page-enter">
            <div className="mb-8">
                <h1 className="text-3xl font-black gradient-text mb-1">Fest Events</h1>
                <p className="text-muted">Join events, earn points, meet people</p>
            </div>

            {/* Category tabs */}
            <div className="flex gap-2 overflow-x-auto pb-2 mb-8">
                {CATEGORIES.map(cat => {
                    const icons = { All: '🎯', Technical: '💻', Cultural: '🎭', Business: '💼', Gaming: '🎮', Creative: '🎨' };
                    return (
                        <button key={cat} onClick={() => { setCategory(cat); setLoading(true); }}
                            className={`flex-shrink-0 px-5 py-2.5 rounded-xl text-sm font-medium transition-all border ${category === cat
                                    ? 'border-cyan-400/50 text-cyan-300 bg-cyan-500/10'
                                    : 'border-white/10 text-muted hover:text-white'
                                }`}>
                            {icons[cat]} {cat}
                        </button>
                    );
                })}
            </div>

            {/* Events grid */}
            {loading ? (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {[...Array(6)].map((_, i) => (
                        <div key={i} className="glass-card p-5">
                            <div className="skeleton h-4 w-20 mb-3 rounded-full" />
                            <div className="skeleton h-5 w-40 mb-2" />
                            <div className="skeleton h-3 w-full mb-2" />
                            <div className="skeleton h-3 w-3/4" />
                        </div>
                    ))}
                </div>
            ) : events.length === 0 ? (
                <div className="glass-card p-16 text-center">
                    <p className="text-5xl mb-4">🎪</p>
                    <p className="text-xl font-bold mb-2">No events in this category</p>
                    <p className="text-muted">Check back later or explore other categories</p>
                </div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                    {events.map(e => (
                        <EventCard key={e.id} event={e}
                            isJoined={joinedIds.has(e.id)}
                            onToggle={fetchEvents} 
                            onReviewClick={setReviewModalEvent}
                        />
                    ))}
                </div>
            )}
            
            {reviewModalEvent && (
                <ReviewsModal event={reviewModalEvent} onClose={() => setReviewModalEvent(null)} />
            )}
        </div>
    );
}
